import { TCertificate } from "@/types";

export const Specialcertificates: TCertificate[] = [
  {
    image: "/cert-specialization.png",
    title: "Meta Front-End Developer Certificate",
    subtitle: "Front-End Developer",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Front-End Development",
    link: "",
  },
  {
    image: "/cert-specialization.png",
    title: "ILEAD Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "MAXWELL LEADERSHIP FOUNDATION",
    category: "Leadership",
    link: "",
  },
  {
    image: "/cert-specialization.png",
    title: "Digital Skills FOUNDATION Certificate",
    subtitle: "Digital Skills",
    date: "December 2024",
    organization: "Google Digital Skills for Africa",
    category: "Digital Skills",
    link: "",
  },
];
export const Othercertificates: TCertificate[] = [
  {
    image: "/cert-coursera.png",
    title: "Version Control with Git",
    subtitle: "Version Control",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Version Control",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Introduction to HTML And Css",
    subtitle: "HTML5 and CSS3",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "HTML5 and CSS3",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Advanced React",
    subtitle: "React",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "React",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Principles of UX/UI Design",
    subtitle: "UX/UI Design",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Design",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "React Basics",
    subtitle: "React",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "React",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "HTML and CSS in depth",
    subtitle: "HTML5 and CSS3",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "HTML5 and CSS3",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Coding Interview Preparation",
    subtitle: "Interview Preparation",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Interview",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Front-End Developer Capstone",
    subtitle: "Front-End Developer",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Front-End Development",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "iDo Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "MAXWELL LEADERSHIP FOUNDATION",
    category: "Leadership",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "iChoose Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "MAXWELL LEADERSHIP FOUNDATION",
    category: "Leadership",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Programming for Everybody (Getting Started with Python)",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Python Data Structures",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
  {
    image: "/cert-coursera.png",
    title: "Using Python to Access Web Data",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
];
