import { TCertificate } from "@/types";

export const DigitalSkillscertificates: TCertificate[] = [
  {
    image: "/cert-specialization.png",
    title: "Digital Skills Foundation Certificate",
    subtitle: "Digital Skills",
    date: "December 2024",
    organization: "Google Digital Skills for Africa",
    category: "Digital Skills",
    link: "",
  },
];
export const WebdevCertificates: TCertificate[] = [
  {
    image: "/cert-specialization.png",
    title: "Meta Front-End Developer Certificate",
    subtitle: "Front-End Developer",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Front-End Development",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Version Control with Git",
    subtitle: "Version Control",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Version Control",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Introduction to HTML And Css",
    subtitle: "HTML5 and CSS3",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "HTML5 and CSS3",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Advanced React",
    subtitle: "React",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "React",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Principles of UX/UI Design",
    subtitle: "UX/UI Design",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Design",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "React Basics",
    subtitle: "React",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "React",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "HTML and CSS in depth",
    subtitle: "HTML5 and CSS3",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "HTML5 and CSS3",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Coding Interview Preparation",
    subtitle: "Interview Preparation",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Interview",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Front-End Developer Capstone",
    subtitle: "Front-End Developer",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Front-End Development",
    link: "",
  },
];
export const LeadershipCertificates: TCertificate[] = [
  {
    image: "/cert-course.png",
    title: "iDo Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "Maxwell Leadership Foundation",
    category: "Leadership",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "iChoose Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "Maxwell Leadership Foundation",
    category: "Leadership",
    link: "",
  },
  {
    image: "/cert-specialization.png",
    title: "iLead Leadership Certificate",
    subtitle: "Leadership",
    date: "December 2024",
    organization: "Maxwell Leadership Foundation",
    category: "Leadership",
    link: "",
  },
];
export const PythonCertificates: TCertificate[] = [
  {
    image: "/cert-course.png",
    title: "Programming for Everybody (Getting Started with Python)",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Python Data Structures",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
  {
    image: "/cert-course.png",
    title: "Using Python to Access Web Data",
    subtitle: "Python",
    date: "December 2024",
    organization: "Coursera Meta",
    category: "Python",
    link: "",
  },
];

export const certificates = [
  {
    category: "Web Development",
    certificates: WebdevCertificates,
  },
  {
    category: "Digital Skills",
    certificates: DigitalSkillscertificates,
  },
  {
    category: "Leadership",
    certificates: LeadershipCertificates,
  },
  {
    category: "Python",
    certificates: PythonCertificates,
  },
];
